//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace YardController.Web.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
internal static class Messages
{
    private static ResourceManager? resourceMan;

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    internal static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                var temp = new ResourceManager("YardController.Web.Resources.Messages", typeof(Messages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    internal static CultureInfo? Culture { get; set; }

    /// <summary>
    ///   Looks up a localized string similar to Route {0}-{1} set.
    /// </summary>
    internal static string RouteSet => ResourceManager.GetString("RouteSet", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Route {0}-{1} cleared.
    /// </summary>
    internal static string RouteCleared => ResourceManager.GetString("RouteCleared", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to All routes cleared.
    /// </summary>
    internal static string AllRoutesCleared => ResourceManager.GetString("AllRoutesCleared", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to No train route found from signal {0} to signal {1}.
    /// </summary>
    internal static string RouteNotFound => ResourceManager.GetString("RouteNotFound", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Conflict with locked points: {0}.
    /// </summary>
    internal static string RouteConflict => ResourceManager.GetString("RouteConflict", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Point {0} set to {1}.
    /// </summary>
    internal static string PointSet => ResourceManager.GetString("PointSet", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to No such point number: {0}.
    /// </summary>
    internal static string PointNotFound => ResourceManager.GetString("PointNotFound", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Invalid point command: {0}.
    /// </summary>
    internal static string PointInvalidCommand => ResourceManager.GetString("PointInvalidCommand", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Point {0} is locked.
    /// </summary>
    internal static string PointLocked => ResourceManager.GetString("PointLocked", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Click a signal to start a route.
    /// </summary>
    internal static string SelectFromSignal => ResourceManager.GetString("SelectFromSignal", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to From: {0} — click destination signal.
    /// </summary>
    internal static string SelectToSignal => ResourceManager.GetString("SelectToSignal", Culture)!;
}
